runtime: custom
env: flex

# Optional: Specify the service name
# service: your-service-name

# Entrypoint for your application
entrypoint: bun run start

# Optional: Define environment variables
# env_variables:
# NODE_ENV: production

# Optional: Configure automatic scaling
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 2
